### ISSUE TITLE
Dashboard not populated with data

### ISSUE THREAD

**Issue by cityshrimp** [amiracle/splunk_app_evidentio#1] opened 2017-04-26 17:19 UTC
I think there might be some issues with the queries used.  I tried running this in search:

`index=main sourcetype=aws-evidentio message.Records{}.Sns.Message &gt; 1  | spath input=message.Records{}.Sns.Message|  rename "included{}.attributes.risk_level" as "Severity" | stats count by Severity`

It seems `message.Records{}.Sns.Message` is not recognized.  The only way I can get this to work is if I add a Field Alias and map `Records{}.Sns.Message` then use that alias instead.

Is that the only solution?  Is there a way for me to do this without setting up Field Aliases?

**Comment by amiracle** [comment] 2017-05-07 18:38
I think the issue is that the method that Evident sends the data to Splunk changed since I wrote the original app. The fix is actually just making the change in the dashboards to reflect the change in the way evident formatted the JSON object.

**Comment by cityshrimp** [comment] 2017-05-09 18:10
I'm quite new to Splunk, could you show me how I can do that without the use of Field Aliases?  That's really the only way I got it work.  It would be ideal if the App could work without needing to take any extra steps.

**Comment by amiracle** [comment] 2017-05-10 15:05
You don't need to make any changes to the Field Aliases since Splunk automatically pulls in the new field from the JSON event. The only change that needs to happen is in the dashboard itself, where the old field was `message.Records{}.Sns.Message` and the new one is `Records{}.Sns.Message` . I'm trying to test it out with my instance, once I get it tested, I'll make the changes to the dashboard in this app and publish the update (here and on Splunkbase.)

**Comment by cityshrimp** [comment] 2017-05-10 23:06
Oh nice, that worked!  Yes, if you could please update the code here and in Splunkbase, that would be great.

**Comment by amiracle** [comment] 2017-08-03 03:57
This issue has been resolved in the latest version of the app (1.2). It will be released once it has been vetted and certified for Splunk and Splunk Cloud.

**Closed** 2017-08-03 04:08 UTC
Labels: enhancement, question
